import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  safeArea: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    paddingTop: 60,
  },
  imageContainer: {
    flex: 2,
    backgroundColor: "#ADEBB3",
    justifyContent: "center",
    alignItems: "center",
  },
  verifyImageContainer: {
    flex: 1,
    backgroundColor: "#ffffffff",
    justifyContent: "center",
    alignItems: "center",
  },
  image: { width: 412, height: 577 },
  textContainer: { flex: 1, padding: 20, justifyContent: "center" },
  verifyTextContainer: { flex: 1, padding: 20, alignItems: "center" },
  title: { fontSize: 28, fontWeight: "bold", marginBottom: 10 },
  subtitle: { fontSize: 15, color: "#666", marginBottom: 30 },
  buttonContainer: { flexDirection: "row", justifyContent: "space-between" },
  signUpButton: {
    flex: 1,
    marginRight: 10,
    padding: 15,
    borderWidth: 1,
    borderColor: "#000",
    borderRadius: 8,
    alignItems: "center",
  },
  loginButton: {
    flex: 1,
    marginLeft: 10,
    padding: 15,
    backgroundColor: "#ADEBB3",
    borderRadius: 8,
    alignItems: "center",
  },
  buttonText: { color: "#000", fontWeight: "bold" },
  resendText: { color: "#000", fontWeight: "bold", marginBottom: 30 },
  Signupcontainer: { flexGrow: 1, backgroundColor: "#fff" },
  header: {
    paddingTop: 60,
    alignItems: "center",
  },
  editIcon: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#ADEBB3",
    padding: 6,
    borderRadius: 50,
    borderWidth: 6,
    borderColor: "#fff",
  },
  imageWrapper: {
    position: "relative",
  },
  headerText: {
    fontSize: 22,
    fontWeight: "bold",
  },
  profileContainer: {
    alignItems: "center",
    marginVertical: 30,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  profileName: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 10,
  },
  rentButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
    marginRight: 10,
  },
  rentText: {
    color: "#fff",
    fontWeight: "bold",
  },
  info: {
    flex: 1,
  },
  carName: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 6,
  },
  filterContainer: {
    flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 15,
    paddingRight: 15,
    paddingLeft: 15,
  },
  filterTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  details: {
    fontSize: 13,
    color: "gray",
    marginBottom: 8,
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  detailButton: {
    borderWidth: 1,
    borderColor: "#000",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
  },
  detailText: {
    color: "#000",
    fontWeight: "bold",
  },
  carImage: {
    width: 120,
    height: 80,
    marginRight: 10,
  },
  card: {
    flexDirection: "row",
    marginBottom: 20,
    alignItems: "center",
  },
  input: {
    width: "100%",
    height: 50,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
  },
  linkText: {
    marginTop: 20,
    color: "blue",
  },
  button: {
    width: "100%",
    height: 50,
    backgroundColor: "#ADEBB3",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    marginTop: 10,
    padding: 15,
    borderRadius: 8,
  },
  hint: {
    fontSize: 12,
    color: "#666",
    marginBottom: 12,
  },
  loginText: { color: "#000", fontWeight: "bold" },
  Formcontainer: {
    flex: 2,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 20,
  },
  codeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "80%",
    alignSelf: "center",
  },
  codeinput: {
    borderWidth: 1,
    borderColor: "#ccc",
    width: 50,
    height: 50,
    textAlign: "center",
    fontSize: 20,
    borderRadius: 8,
  },
  verifyButton: {
    marginLeft: 10,
    padding: 15,
    backgroundColor: "#ADEBB3",
    borderRadius: 8,
    alignItems: "center",
  },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: "#eee",
    margin: 5,
  },
  chipSelected: {
    backgroundColor: "#f8f8f8", // green
  },
  chipText: {
    fontSize: 14,
    color: "#333",
  },
  chipTextSelected: {
    color: "#fff",
    fontWeight: "600",
  },
  icon: {
    position: "absolute",
    right: 12,
    top: "50%",
    transform: [{ translateY: -18 }], // centers the icon
  },
  passwordContainer: {
    width: "100%",
    marginVertical: 10,
    position: "relative",
  },
});
